[package]
name = "workplace-server"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.21.0"
eframe = "0.26.1"
once_cell = "1.19.0"
workplace-common = { path = "../common" }